config/routes.rb
Rails.application.routes.draw do
  root 'dashboard#index'
  resources :accounts,
            :costs_categories,
            :incomes_categories,
            :costs_operations,
            :incomes_operations,
            :dashboard,
            :all_operations

end

app/models/account.rb
class Account < ApplicationRecord
  has_many :incomes_operations
  has_many :costs_operations
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/costs_category.rb
class CostsCategory < ApplicationRecord
  has_many :costs_operations
end

app/models/costs_operation.rb
class CostsOperation < ApplicationRecord
  belongs_to :costs_category
  belongs_to :account
end

app/models/incomes_category.rb
class IncomesCategory < ApplicationRecord
  has_many :incomes_operations
end

app/models/incomes_operation.rb
class IncomesOperation < ApplicationRecord
  belongs_to :incomes_category
  belongs_to :account
end

app/controllers/accounts_controller.rb
# accounts
class AccountsController < ApplicationController
  before_action :find_account, only: %i[show edit destroy update]
  def index
    @accounts = Account.all
  end

  def show; end

  def new
    @account = Account.new
  end

  def create
    @account = Account.new(account_params)
    if @account.save
      redirect_to accounts_path, notice: 'Счет создан'
    else
      render :new
    end
  end

  def edit; end

  def update
    if @account.update_attributes(account_params)
      redirect_to accounts_path, notice: 'Счет изменен'
    else
      render :edit
    end
  end

  def destroy
    @account.destroy
    redirect_to root_path, notice: 'Счет удален'
  end

  private

  def find_account
    @account = Account.find(params[:id])
  end

  def account_params
    params.require(:account).permit(:title,
                                    :icon,
                                    :color,
                                    :balance)
  end
end

app/controllers/all_operations_controller.rb
class AllOperationsController < ApplicationController
  def index
    if category = params[:category_id]
      @costs_operations = CostsOperation.where(costs_category_id: category).order(:datetime)
    else
      @costs_operations = CostsOperation.all.order(:datetime)
    end
    #@incomes_operations = IncomesOperation.all.order(:datetime)
  end

  private

  def operation_params
    params.require(:all_operation).permit(:category_id)
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/costs_categories_controller.rb
# Costs Categories
class CostsCategoriesController < ApplicationController
  before_action :find_costs_category, only: %i[show edit destroy update]
  def index; end

  def show; end

  def new
    @costs_category = CostsCategory.new
  end

  def create
    @costs_category = CostsCategory.new(costs_category_params)
    if @costs_category.save
      redirect_to root_path, notice: 'Категория расхода успешно создана'
    else
      render :new
    end
  end

  def edit; end

  def update
    if @costs_category.update_attributes(costs_category_params)
      redirect_to root_path, notice: 'Категория расхода успешно изменен'
    else
      render :edit
    end
  end

  def destroy
    @costs_category.destroy
    redirect_to root_path, notice: 'Категория расхода успешно удален'
  end

  private

  def find_costs_category
    @costs_category = CostsCategory.find(params[:id])
  end

  def costs_category_params
    params.require(:costs_category).permit(:title, :icon, :color, :month_budget)
  end
end

app/controllers/costs_operations_controller.rb
# Costs Operations
class CostsOperationsController < ApplicationController
  before_action :find_costs_operation, only: %i[show edit destroy update]
  def index; end

  def new
    @costs_operation = CostsOperation.new
  end

  def create
    @costs_operation = CostsOperation.new(costs_operation_params)
    if @costs_operation.save
      redirect_to root_path, notice: 'Операция добавлена'
    else
      render :new
    end
  end

  def show; end

  def edit; end

  def update
    if @costs_operation.update_attributes(costs_operation_params)
      redirect_to all_operations_path, notice: 'Операция успешно изменена'
    else
      render :edit
    end
  end

  def destroy
    @costs_operation.destroy
    respond_to do |format|
      format.html { redirect_to all_operations_path, notice: 'Операция удалена' }
      format.json { head :no_content }
    end
  end
  private

  def find_costs_operation
    @costs_operation = CostsOperation.find(params[:id])
  end

  def costs_operation_params
    params.require(:costs_operation).permit(:costs_category_id,
                                            :value,
                                            :account_id,
                                            :datetime)
  end
end

app/controllers/dashboard_controller.rb
class DashboardController < ApplicationController
  def index
    @costs_categories = CostsCategory.all
    @incomes_categories = IncomesCategory.all
  end
end

app/controllers/incomes_categories_controller.rb
class IncomesCategoriesController < ApplicationController
  before_action :set_incomes_category, only: %i[show edit update destroy]

  def index
    @incomes_categories = IncomesCategory.all
  end

  def show; end

  def new
    @incomes_category = IncomesCategory.new
  end

  def edit; end

  def create
    @incomes_category = IncomesCategory.new(incomes_category_params)

    respond_to do |format|
      if @incomes_category.save
        format.html { redirect_to root_path, notice: 'Income category was successfully created.' }
        format.json { render :show, status: :created, location: @incomes_category }
      else
        format.html { render :new }
        format.json { render json: @incomes_category.errors, status: :unprocessable_entity }
      end
    end
  end

  def update
    respond_to do |format|
      if @incomes_category.update(incomes_category_params)
        format.html { redirect_to root_path, notice: 'Income category was successfully updated.' }
        format.json { render root_path, status: :ok, location: @incomes_category }
      else
        format.html { render :edit }
        format.json { render json: @incomes_category.errors, status: :unprocessable_entity }
      end
    end
  end

  def destroy
    @incomes_category.destroy
    respond_to do |format|
      format.html { redirect_to incomes_categories_url, notice: 'Income category was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private

  def set_incomes_category
    @incomes_category = IncomesCategory.find(params[:id])
  end

  def incomes_category_params
    params.require(:incomes_category).permit(:title, :icon, :color)
  end
end

app/controllers/incomes_operations_controller.rb
# Operations for budgets
class IncomesOperationsController < ApplicationController
  before_action :find_positive_operation, only: %i[show edit destroy update]
  def index; end

  def new
    @incomes_operation = IncomesOperation.new
  end

  def create
    @incomes_operation = IncomesOperation.new(incomes_operation_params)
    if @incomes_operation.save
      redirect_to root_path, notice: 'Операция добавлена'
    else
      render :new
    end
  end

  def show; end

  def edit; end

  def update; end

  private

  def find_positive
    @incomes_operation = IncomesOperation.find(params[:id])
  end

  def incomes_operation_params
    params.require(:incomes_operation).permit(:incomes_category_id,
                                              :value,
                                              :account_id,
                                              :datetime)
  end
end

app/helpers/accounts_helper.rb
module AccountsHelper
  def calc_balance(account)
    positive_sum = account.incomes_operations.pluck(:value).inject(0){ |result, elem| result + elem }
    negative_sum = account.costs_operations.pluck(:value).inject(0){ |result, elem| result + elem }
    account.balance + positive_sum - negative_sum
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/dashboard_helper.rb
# Dashboard helper
module DashboardHelper
  def calc_costs(category)
    sum = 0
    category.costs_operations.each do |operation|
      sum += operation.value
    end
    sum
  end

  def calc_income(income_category)
    sum = 0
    income_category.incomes_operations.each do |operation|
      sum += operation.value
    end
    sum
  end

  def contrast_color(color)
    rgbval = color.hex
    r = rgbval >> 16
    g = (rgbval & 652_80) >> 8
    b = rgbval & 255
    brightness = r * 0.299 + g * 0.587 + b * 0.114
    brightness > 160 ? 'dark-contrast' : 'light-contrast'
  end
end

app/helpers/income_categories_helper.rb
module IncomeCategoriesHelper
end

app/views/accounts/_form.html.haml
.form
  = form_for @account, html: { multipart: true } do |f|
    - if @account.errors.any?
      = @account.errors.count
      - @account.errors.full_messages.each do |msg|
        %li= msg

    .form-group.row
      = f.label :title, class: 'col-sm-2 col-form-label'
      .col-sm-10
        = f.text_field :title, class: 'form-control'

    .form-group.row
      = f.label :icon, class: 'col-sm-2 col-form-label'
      .col-sm-10
        = f.text_field :icon, class: 'form-control'

    .form-group.row
      = f.label :color, class: 'col-sm-2 col-form-label'
      .col-sm-10
        = f.text_field :color, class: 'form-control'

    .form-group.row
      = f.label :balance, class: 'col-sm-2 col-form-label'
      .col-sm-10
        = f.text_field :balance, class: 'form-control'

    = f.submit 'сохранить', class: 'btn btn-success'

app/views/accounts/index.html.haml
%ol.breadcrumb
  %li.breadcrumb-item
    %a{:href => "#"} Категории
  %li.breadcrumb-item.active Счета
.row
  - @accounts.each do |account|
    .col-xl-3.col-sm-6.mb-3
      .card.text-white.o-hidden.h-100{style: "background-color: ##{account.color}"}
        .card-body
          .card-body-icon
            = fa_icon account.icon || 'list'
          = link_to account.title || 'Безымянный счет', edit_account_path(account), class: 'mr-5'
          .mr-5= calc_balance(account)
        = link_to new_incomes_operation_path(account: account.id), class: 'card-footer text-white clearfix small z-1' do
          %span.float-left Добавить доход
          %span.float-right
            %i.fa.fa-angle-right
  .col-xl-3.col-sm-6.mb-3
    .card.text-white.bg-success.o-hidden.h-100
      .card-body
        .card-body-icon
          = fa_icon 'plus'
        = link_to 'Добавить категорию', new_account_path, class: 'mr-5 text-white'
      %a.card-footer.text-white.clearfix.small.z-1{:href => "#"}
        %span.float-left Добавить доход
        %span.float-right
          %i.fa.fa-angle-right

app/views/accounts/new.html.haml
= render 'form'

app/views/budgets/_form.html.haml
.form
  = form_for @budget, html: { multipart: true } do |f|
    - if @budget.errors.any?
      = @budget.errors.count
      - @budget.errors.full_messages.each do |msg|
        %li= msg

    .form-group.row
      = f.label :title, class: 'col-sm-2 col-form-label'
      .col-sm-10
        = f.text_field :title, class: 'form-control'

    .form-group.row
      = f.label :icon, class: 'col-sm-2 col-form-label'
      .col-sm-10
        = f.text_field :icon, class: 'form-control'

    .form-group.row
      = f.label :color, class: 'col-sm-2 col-form-label'
      .col-sm-10
        = f.text_field :color, class: 'form-control'

    .form-group.row
      = f.label :value, class: 'col-sm-2 col-form-label'
      .col-sm-10
        = f.text_field :value, class: 'form-control'

    = f.submit 'сохранить', class: 'btn btn-success'

app/views/budgets/index.html.haml
%ol.breadcrumb
  %li.breadcrumb-item
    %a{:href => "#"} Категории
  %li.breadcrumb-item.active Счета
.row
  - @budgets.each do |budget|
    .col-xl-3.col-sm-6.mb-3
      .card.text-white.o-hidden.h-100{style: "background-color: #{budget.color}"}
        .card-body
          .card-body-icon
            = fa_icon budget.icon || 'list'
          .mr-5= budget.title || 'Безымянный счет'
          .mr-5= budget.value
        = link_to new_operation_path(budget: budget.id), class: 'card-footer text-white clearfix small z-1' do
          %span.float-left Добавить доход
          %span.float-right
            %i.fa.fa-angle-right
  .col-xl-3.col-sm-6.mb-3
    .card.text-white.bg-success.o-hidden.h-100
      .card-body
        .card-body-icon
          = fa_icon 'plus'
        = link_to 'Добавить категорию', new_budget_path, class: 'mr-5 text-white'
      %a.card-footer.text-white.clearfix.small.z-1{:href => "#"}
        %span.float-left Добавить доход
        %span.float-right
          %i.fa.fa-angle-right

app/views/categories/_form.html.haml
.form
  = form_for @category, html: { multipart: true } do |f|
    - if @category.errors.any?
      = @category.errors.count
      - @category.errors.full_messages.each do |msg|
        %li= msg

    .form-group.row
      = f.label :title, class: 'col-sm-2 col-form-label'
      .col-sm-10
        = f.text_field :title, class: 'form-control'

    .form-group.row
      = f.label :icon, class: 'col-sm-2 col-form-label'
      .col-sm-10
        = f.text_field :icon, class: 'form-control'

    .form-group.row
      = f.label :color, class: 'col-sm-2 col-form-label'
      .col-sm-10
        = f.text_field :color, class: 'form-control'

    .form-group.row
      = f.label :month_budget, class: 'col-sm-2 col-form-label'
      .col-sm-10
        = f.text_field :month_budget, class: 'form-control'

    = f.submit 'сохранить', class: 'btn btn-success'

app/views/costs_categories/_form.html.haml
.form
  = form_for @costs_category, html: { multipart: true } do |f|
    - if @costs_category.errors.any?
      = @costs_category.errors.count
      - @costs_category.errors.full_messages.each do |msg|
        %li= msg

    .form-group.row
      = f.label :title, class: 'col-sm-2 col-form-label'
      .col-sm-10
        = f.text_field :title, class: 'form-control'

    .form-group.row
      = f.label :icon, class: 'col-sm-2 col-form-label'
      .col-sm-10
        = f.text_field :icon, class: 'form-control'

    .form-group.row
      = f.label :color, class: 'col-sm-2 col-form-label'
      .col-sm-10
        = f.text_field :color, class: 'pick-a-color form-control'
 
    .form-group.row
      = f.label :month_budget, class: 'col-sm-2 col-form-label'
      .col-sm-10
        = f.text_field :month_budget, class: 'form-control'

    = f.submit 'сохранить', class: 'btn btn-success'

app/views/costs_categories/new.html.haml
= render 'form'

app/views/costs_operations/_form.html.haml
.form
  = form_for @costs_operation do |f|
    - if @costs_operation.errors.any?
      = @costs_operation.errors.count
      - @costs_operation.errors.full_messages.each do |msg|
        %li= msg

    .form-group.row
      = f.label 'Счет', class: 'col-sm-2 col-form-label'
      .col-sm-10
        = f.select :account_id, options_from_collection_for_select(Account.all, :id, :title, @costs_operation.account_id ), {}, class: 'form-control'

    .form-group.row
      = f.label 'Категория', class: 'col-sm-2 col-form-label'
      .col-sm-10
        = f.select :costs_category_id, options_from_collection_for_select(CostsCategory.all, :id, :title, @costs_operation.costs_category_id || params[:category]), {}, class: 'form-control'

    .form-group.row
      = f.label 'Сумма', class: 'col-sm-2 col-form-label'
      .col-sm-10
        = f.number_field :value, class: 'form-control'
 
    .form-group.row
      = f.label :datetime, class: 'col-sm-2 col-form-label'
      .col-sm-10
        = f.date_field :datetime, class: 'form-control'

    = f.submit 'сохранить', class: 'btn btn-success'

app/views/costs_operations/edit.html.haml
= render 'form'

app/views/costs_operations/new.html.haml
= render 'form'

app/views/dashboard/index.html.haml
%ol.breadcrumb
  %li.breadcrumb-item
    %a{:href => "#"} Категории 
  %li.breadcrumb-item.active Расходы
.row
  - @costs_categories.each do |category|
    .col-xl-3.col-sm-6.mb-3
      .card.o-hidden.h-100{style: "background-color: ##{category.color};", class: contrast_color(category.color)}
        .card-body
          .card-body-icon
            = fa_icon category.icon || 'list'
          = link_to category.title || 'Безымянная категория', edit_costs_category_path(category), class: 'mr-5'
          .mr-5 #{calc_costs(category)} / #{category.month_budget || 'Не задано'}
        = link_to new_costs_operation_path(category: category.id), class: 'card-footer clearfix small z-1' do
          %span.float-left Добавить расход
          %span.float-right
            %i.fa.fa-angle-right
  .col-xl-3.col-sm-6.mb-3
    .card.text-white.bg-success.o-hidden.h-100
      .card-body
        .card-body-icon
          = fa_icon 'plus'
        = link_to 'Добавить категорию', new_costs_category_path, class: 'mr-5 text-white'
      %a.card-footer.text-white.clearfix.small.z-1{:href => "#"}
        %span.float-left Добавить расход
        %span.float-right
          %i.fa.fa-angle-right
%ol.breadcrumb
  %li.breadcrumb-item
    %a{:href => "#"} Категории 
  %li.breadcrumb-item.active Доходы
.row
  - @incomes_categories.each do |category|
    .col-xl-3.col-sm-6.mb-3
      .card.text-white.o-hidden.h-100{style: "background-color: ##{category.color}"}
        .card-body
          .card-body-icon
            = fa_icon category.icon || 'list'
          = link_to category.title || 'Безымянная категория', edit_incomes_category_path(category), class: 'mr-5'
          .mr-5 #{calc_income(category)} в этом месяце
        = link_to new_incomes_operation_path(category: category.id), class: 'card-footer text-white clearfix small z-1' do
          %span.float-left Добавить доход
          %span.float-right
            %i.fa.fa-angle-right
  .col-xl-3.col-sm-6.mb-3
    .card.text-white.bg-success.o-hidden.h-100
      .card-body
        .card-body-icon
          = fa_icon 'plus'
        = link_to 'Добавить категорию', new_incomes_category_path, class: 'mr-5 text-white'
      %a.card-footer.text-white.clearfix.small.z-1{:href => "#"}
        %span.float-left Добавить доход
        %span.float-right
          %i.fa.fa-angle-right

app/views/dashboard/template_index.html.haml
%ol.breadcrumb
  %li.breadcrumb-item
    %a{:href => "#"} 25000 р 
  %li.breadcrumb-item.active 30000 р
.row
  .col-xl-3.col-sm-6.mb-3
    .card.text-white.bg-primary.o-hidden.h-100
      .card-body
        .card-body-icon
          = fa_icon 'shopping-basket'
        .mr-5 Продукты
        .mr-5 2500/3000
      %a.card-footer.text-white.clearfix.small.z-1{:href => "#"}
        %span.float-left Добавить операцию
        %span.float-right
          %i.fa.fa-angle-right
  .col-xl-3.col-sm-6.mb-3
    .card.text-white.bg-warning.o-hidden.h-100
      .card-body
        .card-body-icon
          = fa_icon 'beer'
        .mr-5 Развлечения
      %a.card-footer.text-white.clearfix.small.z-1{:href => "#"}
        %span.float-left Добавить операцию
        %span.float-right
          %i.fa.fa-angle-right
  .col-xl-3.col-sm-6.mb-3
    .card.text-white.bg-success.o-hidden.h-100
      .card-body
        .card-body-icon
          = fa_icon 'gift'
        .mr-5 Подарки
      %a.card-footer.text-white.clearfix.small.z-1{:href => "#"}
        %span.float-left Добавить операцию
        %span.float-right
          %i.fa.fa-angle-right
  .col-xl-3.col-sm-6.mb-3
    .card.text-white.bg-danger.o-hidden.h-100
      .card-body
        .card-body-icon
          = fa_icon 'bus'
        .mr-5 Транспорт
      %a.card-footer.text-white.clearfix.small.z-1{:href => "#"}
        %span.float-left Добавить операцию
        %span.float-right
          %i.fa.fa-angle-right
.row
  .col-xl-3.col-sm-6.mb-3
    .card.text-white.bg-secondary.o-hidden.h-100
      .card-body
        .card-body-icon
          = fa_icon 'shopping-basket'
        .mr-5 Продукты
      %a.card-footer.text-white.clearfix.small.z-1{:href => "#"}
        %span.float-left Добавить операцию
        %span.float-right
          %i.fa.fa-angle-right
  .col-xl-3.col-sm-6.mb-3
    .card.text-white.bg-dark.o-hidden.h-100
      .card-body
        .card-body-icon
          = fa_icon 'beer'
        .mr-5 Развлечения
      %a.card-footer.text-white.clearfix.small.z-1{:href => "#"}
        %span.float-left Добавить операцию
        %span.float-right
          %i.fa.fa-angle-right
  .col-xl-3.col-sm-6.mb-3
    .card.text-white.bg-info.o-hidden.h-100
      .card-body
        .card-body-icon
          = fa_icon 'gift'
        .mr-5 Подарки
      %a.card-footer.text-white.clearfix.small.z-1{:href => "#"}
        %span.float-left Добавить операцию
        %span.float-right
          %i.fa.fa-angle-right
  .col-xl-3.col-sm-6.mb-3
    .card.text-white.bg-warning.o-hidden.h-100
      .card-body
        .card-body-icon
          = fa_icon 'bus'
        .mr-5 Транспорт
      %a.card-footer.text-white.clearfix.small.z-1{:href => "#"}
        %span.float-left Добавить операцию
        %span.float-right
          %i.fa.fa-angle-right

app/views/income_categories/_form.html.haml
.form
  = form_for @income_category, html: { multipart: true } do |f|
    - if @income_category.errors.any?
      = @income_category.errors.count
      - @income_category.errors.full_messages.each do |msg|
        %li= msg

    .form-group.row
      = f.label :title, class: 'col-sm-2 col-form-label'
      .col-sm-10
        = f.text_field :title, class: 'form-control'

    .form-group.row
      = f.label :icon, class: 'col-sm-2 col-form-label'
      .col-sm-10
        = f.text_field :icon, class: 'form-control'

    .form-group.row
      = f.label :color, class: 'col-sm-2 col-form-label'
      .col-sm-10
        = f.text_field :color, class: 'form-control'

    = f.submit 'сохранить', class: 'btn btn-success'

app/views/incomes_categories/_form.html.haml
.form
  = form_for @incomes_category, html: { multipart: true } do |f|
    - if @incomes_category.errors.any?
      = @incomes_category.errors.count
      - @incomes_category.errors.full_messages.each do |msg|
        %li= msg

    .form-group.row
      = f.label :title, class: 'col-sm-2 col-form-label'
      .col-sm-10
        = f.text_field :title, class: 'form-control'

    .form-group.row
      = f.label :icon, class: 'col-sm-2 col-form-label'
      .col-sm-10
        = f.text_field :icon, class: 'form-control'

    .form-group.row
      = f.label :color, class: 'col-sm-2 col-form-label'
      .col-sm-10
        = f.text_field :color, class: 'form-control'

    = f.submit 'сохранить', class: 'btn btn-success'

app/views/incomes_categories/edit.html.haml
%h1 Editing income_category

= render 'form'

= link_to 'Show', @income_category
\|
= link_to 'Back', income_categories_path

app/views/incomes_categories/index.html.haml
%h1 Listing income_categories

%table
  %thead
    %tr
      %th Title
      %th Icon
      %th Color
      %th
      %th
      %th

  %tbody
    - @income_categories.each do |income_category|
      %tr
        %td= income_category.title
        %td= income_category.icon
        %td= income_category.color
        %td= link_to 'Show', income_category
        %td= link_to 'Edit', edit_income_category_path(income_category)
        %td= link_to 'Destroy', income_category, method: :delete, data: { confirm: 'Are you sure?' }

%br

= link_to 'New Income category', new_income_category_path

app/views/incomes_categories/new.html.haml
%h1 New income_category

= render 'form'

app/views/incomes_categories/show.html.haml
%p#notice= notice

%p
  %b Title:
  = @income_category.title
%p
  %b Icon:
  = @income_category.icon
%p
  %b Color:
  = @income_category.color

= link_to 'Edit', edit_income_category_path(@income_category)
\|
= link_to 'Back', income_categories_path

app/views/incomes_operations/_form.html.haml
.form
  = form_for @incomes_operation do |f|
    - if @incomes_operation.errors.any?
      = @incomes_operation.errors.count
      - @incomes_operation.errors.full_messages.each do |msg|
        %li= msg

    .form-group.row
      = f.label 'Счет', class: 'col-sm-2 col-form-label'
      .col-sm-10
        = f.select 'account_id', options_for_select(Account.all.map { |c| [c.title, c.id] }), {}, class: 'form-control'

    .form-group.row
      = f.label 'Категория', class: 'col-sm-2 col-form-label'
      .col-sm-10
        = f.select 'incomes_category_id', options_for_select(IncomesCategory.all.map { |c| [c.title, c.id] }, params[:category] ), {}, class: 'form-control'

    .form-group.row
      = f.label 'Сумма', class: 'col-sm-2 col-form-label'
      .col-sm-10
        = f.number_field :value, class: 'form-control'

    .form-group.row
      = f.label :datetime, class: 'col-sm-2 col-form-label'
      .col-sm-10
        = f.text_field :datetime, class: 'form-control datetimepicker'

    = f.submit 'сохранить', class: 'btn btn-success'

app/views/incomes_operations/new.html.haml
= render 'form'

app/views/layouts/application.html.haml
!!!
%html
  %head
    %title Moneysaver
    %meta{:content => "IE=10", "http-equiv" => "x-ua-compatible"}
    %meta{:content => "width=device-width, initial-scale=1.0", :name => "viewport"}
    = csrf_meta_tags
    = stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload'
    = javascript_include_tag 'application', 'data-turbolinks-track': 'reload'
  %body
    %nav.navbar.navbar-expand-lg.navbar-dark.bg-dark
      = link_to 'Money saver', root_path, class: 'navbar-brand'
      %button.navbar-toggler{"aria-controls" => "navbarSupportedContent", "aria-expanded" => "false", "aria-label" => "Toggle navigation", "data-target" => "#navbarSupportedContent", "data-toggle" => "collapse", :type => "button"}
        %span.navbar-toggler-icon
      #navbarSupportedContent.collapse.navbar-collapse
        %ul.navbar-nav.mr-auto
          %li.nav-item{class: current_page?(root_path) ? 'active' : ''}
            = link_to 'Категории', root_path , class: 'nav-link'
          %li.nav-item{class: current_page?(all_operations_path) ? 'active' : ''}
          %li.nav-item.dropdown
            %a#navbarDropdown.nav-link.dropdown-toggle{"aria-expanded" => "false", "aria-haspopup" => "true", "data-toggle" => "dropdown", :href => "#", :role => "button"}
              Операции
            .dropdown-menu{"aria-labelledby" => "navbarDropdown"}
              = link_to 'Все', all_operations_path, class: 'dropdown-item'
              .dropdown-divider
              - CostsCategory.all.each do |category|
                = link_to category.title, all_operations_path(category_id: category.id), class: 'dropdown-item'
          %li.nav-item
            %a.nav-link{:href => "#"} Бюджет
          %li.nav-item{class: current_page?(accounts_path) ? 'active' : ''}
            = link_to 'Счета', accounts_path , class: 'nav-link'
        .my-2.my-lg-0
          .nav-link.my-2.my-sm-0.text-success{:href => "#"} 25000/50000 Р 
        .my-2.my-lg-0
          %a.nav-link.text-light{"data-target" => "#exampleModal", "data-toggle" => "modal"}
            = fa_icon 'sign-out', text: 'Logout'
    .content-wrapper
      .container-fluid
        = yield